#!/bin/bash

# Arguments to add password code request button on a User Edit page.
declare -a ADD_EDIT_CODE_REQUEST_BUTTON=(
    skip AECR_BUTTON_DONE "edit/schema/button[name:pwreq]" --

    before-sibling "edit/schema/button[type:delete]" "button:new" --
    last-child "edit/schema/button:new"
       "type : call"
       "name : pwreq"
       "Label : Create Password Code"
       "task : ?${mode_name}"
       --

    label AECR_BUTTON_DONE --

    )

# Arguments to create response mode for showing the password change code.
declare -a ADD_CODE_REQUEST_MODE=(
    skip ACRM_MODE_DONE "pwreq_page" --

    append_mode "pwreq_page" --
    last-child "pwreq_page"
       "type : form-page"
       "procedure : App_User_Create_Password_Code"

    label ACRM_MODE_DONE --
)

# Arguments to add identity session instructions to autoload.srm
declare -a ADD_SESSION_INFO_TO_AUTOLOAD=(
    skip ASITA_DONE "\$session-type:identity" --

    after-sibling "\$default-mode"
       "\$session-type: identity"
       "\$test-authorized : App_Session_Confirm"
       "\$jump-not-authorized : Login.srm"
    --

    label ASITA_DONE --
)

# Nothing here yet.   Fill this in when the Login.srm script
# is established.
declare -a ADD_RELAXED_AUTHORIZATION_FOR_LOGIN=(

    after-sibling edit/type "session-type : establish" --
    after-sibling edit_submit/type "session-type : establish" --
)


gensfw_srm site/User.srm "${ADD_EDIT_CODE_REQUEST_BUTTON[@]}" "${ADD_CODE_REQUEST_MODE[@]}"
gensfw_srm site/autoload.srm "${ADD_SESSION_INFO_TO_AUTOLOAD[@]}"

