#!/bin/bash

# All variables set here are declared in their respective scripts.
# There is no obligation to set the values here, but this is a
# convenience to allow updating how the scripts run without making
# changes therein.

# Some variables are tagged (required).  What is required is that
# the script needs to value to be set, not that it must be set here.

# in 'setup' script
DBASE="SFW_Starter"        # (required) name of MySQL database
SITE_TITLE="Starter Title" # for <title> and <head> in default.xsl

# Add to list of directories to be created in 'setup' script.
# which otherwise includes "generated", "site", and "sql".

# if [ "${DIR_LIST}" ]; then
#     DIR_LIST=( "${DIR_LIST[@]}" custom)
# fi


# in 'setup_apache' script
SITE_NAME="sfw_starter"    # (required) .conf name and backup hostname

SITE_INDEX="Menu.srm"      # DirectoryIndex value in .conf file.  If
                           # missing, DirectoryIndex will be set to the
                           # first SRM file in 'site' directory.

SITE_URL="mydomain.com"    # ServerName value in .conf file.  If
                           # missing, the ServerName will be set to
                           # the value in the SITE_NAME variable above
                           # AND the SITE_NAME will be added to the
                           # /etc/hosts file to activate for localhost.
          

